# Benefit from https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll.

title: Nanda221 Blog
author: nanda221
email: nandaman221@gmail.com
description: >-
  NodeJS Python Java......I'm good at spell their names.
baseurl: ""
url: ""
github_username:  nanda221

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate